apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-docker-image.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "my-docker-image.name" . }}
